version: '3'
services:
  postgresql:
    image: postgres:latest
    container_name: local-postgresql
    restart: always
    ports: [5432:5432] 
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: br93
      POSTGRES_PASSWORD: root1234
      POSTGRES_DB: postgres
    networks:
      - network
  mysql:
    image: mysql:latest
    container_name: local-mysql
    restart: always
    ports: [3306:3306]
    volumes:
      - mysql-data:/var/lib/mysql
    environment:
      MYSQL_USER: br93
      MYSQL_PASSWORD: root1234
      MYSQL_ROOT_PASSWORD: root1234
      MYSQL_DATABASE: mysql
    networks:
      - network
  
networks:
  network:
    driver:
      bridge

volumes:
  postgres-data:
  pgadmin-data:
  mysql-data: